module.exports = {
  purge: {
    content: ['./src/components/**/*.tsx'],
    enabled: process.env.NODE_ENV === 'publish',
  },
  darkMode: false,
  theme: {
    extend: {
      colors: {
        primary: '#23A6F0',
        'primary-dark': '#2A7CC7',
        success: '#2DC071',
        'success-dark': '#1EB062',
        alert: '#E77C40',
        'alert-dark': '#CA652C',
        danger: '#E74040',
        'danger-dark': '#BB2C2C',
        muted: '#BDBDBD',
        'text-color': '#252B42',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'bg-primary',
    'bg-primary-dark',
    'border-primary',
    'primary',
    'bg-success',
    'bg-success-dark',
    'border-success',
    'success',
    'bg-danger',
    'bg-danger-dark',
    'border-danger',
    'danger',
    'bg-alert',
    'bg-alert-dark',
    'border-alert',
    'alert',
  ],
};
